### ISSUE TITLE
Your module doesn't appear in Chocolat template

### ISSUE THREAD

**Issue by olmoszamudio** [vovayatsyuk/magento-alsoviewed#14]
I have a custom template, and I want that you let me know if I should put one line of code in app/design/frontend/default/chocolat/template/catalog/product/view.phtml to display your module in the same place that I have the Yotpo module (please view http://www.buenamarca.com/celulares-tablets-audifonos-parlantes-bose-tecnologia/celulares-sony-bogota-cali-medellin-barranquilla/sony-xperia-z1-compact-negro.html). Thank you for your advice!

**Comment by vovayatsyuk** [comment]
Hi,
If you theme does not show `product.info.additional` container, you can create alsoviewed block manually directly from product view template:

```php
<?php 
echo $this->getLayout()
    ->createBlock('alsoviewed/widget_products')
    ->setTemplate('yavva/alsoviewed/products.phtml')
    ->setWrapperTemplate('yavva/alsoviewed/wrapper/collateral.phtml') // ->setIsWrapperDisabled(true) if you you custom product list template
    ->setImageWidth(200)
    ->setImageHeight(200)
    ->setProductsCount(4)
    ->setColumnCount(4)
    ->setMode('grid')
    ->setTitle($this->__('Also Viewed Products'))
?>
```

**Comment by olmoszamudio** [comment]
Thank you very much for the prompt reply.

I've added and nothing happens.

Anything else I need to consider?

**Comment by vovayatsyuk** [comment]
1. Please check the following page: `Catalog > Also Viewed Products > Manage relations`.
Do you see the relations on that page?

2. If "no" - check `Catalog > Also Viewed Products > View log`.
If log has some records - press process log button.

**Comment by olmoszamudio** [comment]
1. Yes.
2. Yes, it have some records. I press the button. Now?

Thank you very much!

**Comment by vovayatsyuk** [comment]
Hm..

Do you see the "Sony Xperia Z1 Compact Negro" on `Catalog > Also Viewed Products > Manage relations` page?

p.s. Maybe it's a cache issue? Did you clear the cache after adding alsoviewed code?

**Comment by olmoszamudio** [comment]
Yes, I can see this product!

I clean my cache, and I can't see your extension work yet.

Thank you for your advice!

**Comment by vovayatsyuk** [comment]
Sorry, but I have no idea, why you don't see the block.

Can you send me the code of product view template?

vova.yatsyuk@gmail.com

**Comment by olmoszamudio** [comment]
Thank you,

I just send you the code.

**Comment by vovayatsyuk** [comment]
I forgot one more line in code example:

```php
<?php 
echo $this->getLayout()
    ->createBlock('alsoviewed/widget_products')
    ...
    ->toHtml();
?>
```

I've made a change to previous comment too.

**Comment by olmoszamudio** [comment]
Works perfect!

Thank you!

Best,

Ricardo Olmos | CEO


BUENAMARCA.COM
<https://mailtrack.io/trace/link/2e470c671b3328ab67f14d0062ad513ee53172af?url=http%3A%2F%2Fbuenamarca.com%2F&signature=e6f3b23620e130b4>
 LLC | Phone: (1) 312 869 4532 | Chicago, IL. | PBX: (57) 702 6283 |
Mobile: (57) 312 524 2437 | Bogotá, Colombia | Skype:  olmoszamudio  |
www.buenamarca.com
<https://mailtrack.io/trace/link/c02ccb72674b27b18eb017e92776b0dc0dec6b80?url=http%3A%2F%2Fwww.buenamarca.com%2F&signature=66888627c8bca212>

2015-06-18 15:33 GMT-05:00 Vova Yatsyuk <notifications@github.com>:

**Comment by olmoszamudio** [comment]
Works perfect!

Thank you!

Best,
