### ISSUE TITLE
Ignore Crawlers & Specific IP Addresses

### ISSUE THREAD

**Issue by steigerwald** [vovayatsyuk/magento-alsoviewed#16]
I'm thinking that I might want to ignore robots and maybe even specific IP addresses.  

For robots, Would it be worth adding a setting in the module to enable or disable and then a regex field for users to put their own list of robots that is prepopulated.  If so should we pre populate it with known robots? 

As for ignoring specific IP addresses should it use the default developer ip restriction list or should it be its own setting in the module?

Thanks for the great extension.

**Comment by vovayatsyuk** [comment]
:+1: 

Nice idea to improve module accuracy.

Robots could be really annoying, so we can add a user agent filter with populated value.

Making a filter by IP addresses is easy, but I'm not sure about the results. Does your developers browsing a site so often that they cause many false relations?

**Comment by steigerwald** [comment]
Not developers, thinking about the customer service team who browses the
site daily.

**Comment by vovayatsyuk** [comment]
I've added some popular bots and one Magento specific crawler to default configuration:

```
FlipboardProxy
Twitterbot
MetaURI
facebookexternalhit
008
googlebot
Googlebot
bingbot
msnbot
slurp
Yandex
tm_crawler
```

If you have more to add, write them here.

**Comment by vovayatsyuk** [comment]
More bots to add:

```
redditbot
TweetmemeBot
Applebot
```

> https://ma.ttias.be/what-happens-to-a-new-url-the-first-10-minutes-on-the-internet/

**Comment by steigerwald** [comment]
Nice work! :+1: 

What do you think about the IP address exclusion?
