### ISSUE TITLE
What's the code to use?

### ISSUE THREAD

**Issue by BigBlack** [vovayatsyuk/magento-alsoviewed#18]
Hi, what's the code to use to call this extension on pages?

**Comment by vovayatsyuk** [comment]
I recommend you to use Magento's `Cms > Widget Instances` page at backend for this.

---

If you really need to insert it using the code, you can do that with `xml` layout instructions:

https://github.com/vovayatsyuk/magento-alsoviewed/wiki/Usage#manual

Or with plain php

```php
echo $this->getLayout()
    ->createBlock('alsoviewed/widget_products')
    ->setTitle('Also Viewed Products')
    //->setWrapperTemplate('yavva/alsoviewed/wrapper/collateral.phtml')
    //->setMode('list')
    ->setProductsCount(4)
    ->setColumnCount(4)
    ->setImageWidth(300)
    ->setImageHeight(300)
    ->toHtml();
```
