### ISSUE TITLE
Request new feature：Display Name in Single Line

### ISSUE THREAD

**Issue by cewolf2002** [vovayatsyuk/magento-alsoviewed#19]
Thanks for providing this very useful module.

Could you add this feature "Display Name in Single Line" like Ultimo theme provided?
You can find this option here.
Theme Settings / Category View (Grid Mode) / Display Selected Elements / Display Name in Single Line

If we enabled this, product name will only display in single line.
But in alsoviewed, product name displayed all words.
It makes next line can not align.

**Comment by vovayatsyuk** [comment]
Hi!

Can you provide a link to a store with Ultimo and Alsoviewed extension? 

The module is written using standard magento markup, so I think that styles should be inherited automatically from active theme.

**Comment by cewolf2002** [comment]
Thanks for response.
Those 3 picture captured from my website.

1. Product name only display in single line.
![grid_view](https://cloud.githubusercontent.com/assets/16146906/13690040/448834f4-e768-11e5-8739-e463f9abedf4.png)

2. Full display product name on hoover
![grid_view_on_hoover](https://cloud.githubusercontent.com/assets/16146906/13690050/5b971af2-e768-11e5-96d3-60549594e8df.png)

3. This is alsoviewed displayed.
First product's name is too long, so the price is not aligned.
![also_viewd](https://cloud.githubusercontent.com/assets/16146906/13690080/ac70ef84-e768-11e5-810b-90c89ee6acd2.png)

**Comment by vovayatsyuk** [comment]
I see.. Looks like ultimo uses modified product listing layout.

If you would like to apply Ultimo styles, you need to copy [alsoviewed listing template](https://github.com/vovayatsyuk/magento-alsoviewed/blob/master/app/design/frontend/base/default/template/yavva/alsoviewed/products.phtml) into Ultimo theme folder and modify it according to Ultimo needs.

I dig into [Ultimo theme markup](http://ultimo.infortis-themes.com/demo/default/women.html) and found that theme is using the `single-line-name` class to show product name in one line.

So I think that you may try to add the `single-line-name` class into [alsoviewed grid template](https://github.com/vovayatsyuk/magento-alsoviewed/blob/master/app/design/frontend/base/default/template/yavva/alsoviewed/products.phtml#L62):

```
<ul class="products-grid single-line-name cols-<?php echo $_columnCount ?>">
```

P.S. You may also play with following Ultimo classes:

```
itemgrid
itemgrid-adaptive
itemgrid-3col
single-line-name
centered
hover-effect
equal-height
```

P.P.S. Unfortunately I don't have access to Ultimo sources, and can't say what should be done exactly to achive best results.

**Comment by cewolf2002** [comment]
It works !!!
Thanks so much.  :+1:

**Comment by vovayatsyuk** [comment]
Glad it helped.
