### ISSUE TITLE
Enabled SSL but alsoviewd link always redirect to http://

### ISSUE THREAD

**Issue by cewolf2002** [vovayatsyuk/magento-alsoviewed#20]
We enabled SSL on our magento server in the recent.
But I noticed product's link in alsoviewed section are always link to http://.....
Is there any way to fix it?
Thanks.  :)

**Comment by cewolf2002** [comment]
All area's link use https.
Issue solved after setting {{unsecure_base_url}} to https://www.domain.com
I'm not sure this is the best solution.  :)

**Comment by vovayatsyuk** [comment]
It's a correct solution. 

Magento uses secure url only for a few pages by default.

If you would like to use https for all links, you should change the `System > Configuration > Web > Unsecure > Base Url` config option.
