### ISSUE TITLE
Nothing appears in magento 1.9.2.4

### ISSUE THREAD

**Issue by MaikoHermans** [vovayatsyuk/magento-alsoviewed#21]
I've installed the extension and set it up. My cron is running without any problems but when I go to the product page of my test product (I have created 4 test products) it doesn't show up.

I even tried making a static block containing a widget for also viewed recommendation and implemented this in my view but that will only echo the <p></p> tag and nothing else.

Do you happen to know what might be wrong? Could it be because I created one test product and copied this 4 times? 

Or could something else be going on?

**Comment by vovayatsyuk** [comment]
Hi! 

First of all, navigate to `Catalog > Also Viewed Products > Log` and check for records there. This is a plain log of future relations. 

If the log is empty after you opened two or more products on the front-end, this means that the module is not working and possible reason for that is a full page cache module with specific behavior.

Please, let me know about `Catalog > Also Viewed Products > Log` grid.

**Comment by MaikoHermans** [comment]
Somehow it shows up now even tho I didn't change anything about it really. However I have one other question while I'm here. I need to get the "you may also like" part into a static block is this possible?

I'm using neoshop as template. I tried adding the following into the local.xml

`<reference name="CUSTOM.BLOCK.NAME">
          <block type="core/template" name="alsoviewed.custom.wrapper" before="-">
              <action method="setTemplate">
                  <template>yavva/alsoviewed/wrapper/collateral.phtml</template>
              </action>
              <block type="alsoviewed/products" name="alsoviewed.list" template="yavva/alsoviewed/products.phtml">
                  <action method="setMode"><mode>grid</mode></action>
                  <action method="setProductsCount"><count>4</count></action>
                  <action method="setColumnCount"><count>4</count></action>
                  <action method="setImageWidth"><width>170</width></action>
                  <action method="setImageHeight"><height>170</height></action>
              </block>
          </block>
      </reference>`

am I doing something wrong? Or if it would be possible to add this block into a widget that would work as well

**Comment by vovayatsyuk** [comment]
1. I thinks it was a cache on cron schedule related issue.
2. You can use the widget inside cms block. However if you'll describe what you want to achieve, it will be easier for me to help you. For now it's not clear to me what you are trying to do.

**Comment by MaikoHermans** [comment]
What I'm trying to do is display the "People who viewed this product also viewed" section in a static block.

Because at this moment it is being displayed at a random spot inside my product page. However when I try to create a widget I don't see a option for this option.

So I'm not able to select "People who viewed this product also viewed" when I create a widget. So at this moment I'm just trying to figure out how I can get this block to show up in my static block.

hope that makes sense?

**Comment by vovayatsyuk** [comment]
Th widget is called `Also Viewed Recommendations`.

See the screenshot of widget interface:

https://github.com/vovayatsyuk/magento-alsoviewed#widget

**Comment by MaikoHermans** [comment]
Alright so what happens is when I add the widget you suggested I get the following result:

![image](https://cloud.githubusercontent.com/assets/6593958/17397830/2bbc05dc-5a3a-11e6-966f-8f1ff2ef499a.png)

While this is the result that I should be getting (this is the "People who viewed this product also viewed" result

![image](https://cloud.githubusercontent.com/assets/6593958/17397849/3f1606e6-5a3a-11e6-85cf-1fc356d07d4c.png)

**Comment by vovayatsyuk** [comment]
Can you provide a link to your site?

**Comment by vovayatsyuk** [comment]
Maybe I've got your point.

Try to add `wrapper_template` attribute into widget code manually:

```
{{widget type="..." wrapper_template="yavva/alsoviewed/wrapper/collateral.phtml" ...}}
```

Alsoviewed module has two wrapper template types:

```
yavva/alsoviewed/wrapper/collateral.phtml - for product view content
yavva/alsoviewed/wrapper/block.phtml - for widgets and blocks
```

**Comment by MaikoHermans** [comment]
can I contact you somewhere private so I can send you the link?
the problem isn't the layout but the products that are actually being shown.
I tried adding the wrapper_template but this didn't change anything as far as I can tell

**Comment by vovayatsyuk** [comment]
I emailed you 10 minutes ago.

So the layout is not a issue? What is the issue? Different products?

Did you select only one value for `Build recommendation` option in [widget popup](https://github.com/vovayatsyuk/magento-alsoviewed#widget)?

To build recommendations for currenlty viewed product only, you should select `Current product` value only.

**Comment by MaikoHermans** [comment]
damn my bad I didn't notice that you mailed me just now. I actually just changed it to "Current product" (again) and this time it worked flawless. I tried everything but somehow it didn't work the first time around I guess haha.

anyway a HUGE thanks for helping me out!!! I appreciate it!

**Comment by vovayatsyuk** [comment]
Glad for you! Good luck!
