### ISSUE TITLE
Request new feature

### ISSUE THREAD

**Issue by cewolf2002** [vovayatsyuk/magento-alsoviewed#22]
Are you planing add also-bought feature, I think your also-viewed is the best.
So I hope you could develope this feature in the future.

**Comment by vovayatsyuk** [comment]
Sorry, but no. I will not add this feature.

It's not a "feature" - it's a completely different backend logic for another extension and I don't have a plans for it.

For now I'm going release [Magento2 version](https://github.com/vovayatsyuk/magento2-alsoviewed) for current module functionality.
