### ISSUE TITLE
How to center also_viewed image and price?

### ISSUE THREAD

**Issue by cewolf2002** [vovayatsyuk/magento-alsoviewed#23]
I noticed my also_viewed product's image and price are align left.
How could I center them?

**Comment by vovayatsyuk** [comment]
I use standard magento markup for product listing. Maybe your theme redefines it? In this case I can't tell you what styles should be applied exactly without seeing a theme.

Try very basic centering style for product items:

```css
.products-grid li.item {
    text-align: center;
}
```

Maybe your theme float these elements, in this case you'll need to apply additional styles. Let me know your page url - it will be much easier to solve this issue.

**Comment by cewolf2002** [comment]
Should I put in the top of this file?
/app/design/frontend/ultimo/default/template/plwhobought/product.phtml

**Comment by cewolf2002** [comment]
I'm using ultimo.

**Comment by vovayatsyuk** [comment]
You should put it into css file.
I don't know where ultimo recommends to place css modifications.

Can you show me the link to your product page with alsoviewed products? Otherwise it will take a lot of time to help you.

**Comment by cewolf2002** [comment]
This is our development server.
https://mgt.gapl.com.tw/vitantonio-pvwh-10-dt.html

**Comment by cewolf2002** [comment]
I found solution.
I put  "text-align: center;" after line 20 in this file.
/skin/frontend/base/default/yavva/alsoviewed/css/alsoviewed.css

Then images and price are centered now.
Thanks for your help.

**Comment by vovayatsyuk** [comment]
👍
