### ISSUE TITLE
Add alsoview to cms page

### ISSUE THREAD

**Issue by danielchicote** [vovayatsyuk/magento-alsoviewed#24]
Hello, this module works great, but i have tried to put a widget on my homepage with all possible rules  but there is no result, the block look always empty.
Is need to add the configuration in the local.xml file?

**Comment by vovayatsyuk** [comment]
Hi,

No, you don't need to do anything more. Maybe your session is clear and module doesn't know what to recommend?

Try to browse some products that has recommendations, and then check the homepage.
