### ISSUE TITLE
Does works the rencently viewed products feature?

### ISSUE THREAD

**Issue by danielchicote** [vovayatsyuk/magento-alsoviewed#25]
I have an also viewed products widget in the home page, but it only appears when i have products in the cart. It's my particular problem?

The widget is configured in viewed, compared and cart mode. And there is no errors on my logs.

**Comment by vovayatsyuk** [comment]
Hi!

Can you follow the steps below to test this issue:

1. Navigate to the homepage and ensure that suggestions are shown for in-cart products
2. Open product pages for each item you have in the cart
3. Empty the cart contents
4. Navigate to the homepage and check suggestions block
