### ISSUE TITLE
Lesti cache block problem

### ISSUE THREAD

**Issue by danielchicote** [vovayatsyuk/magento-alsoviewed#26]
Hello again.

I have an alsoviewed widget in the homepage (via widget in the content editor), and i'm crazy trying to get the punch hole in the lesti cache.

With the AOE tool i can see that in the alsoviewed widget have three blocks one inside the other (product list, block, and finally widget). I have tried to put all of them like lazy and dynamic blocks in the lesti cache configuration, but magento never update the alsoviewed block when i change the session, add products to the cart, etc..

What i'm doing wrong? Is needed to put any refresh action in the configuration? Thank you very much.

**Comment by vovayatsyuk** [comment]
Hi,

it should be enough to add two blocks into LestiFPC config:

- alsoviewed/widget_products
- alsoviewed/products

Don't know why it's not working. I've never seen lesti fpc configuration, can you attach the screenshot here?

**Comment by vovayatsyuk** [comment]
Hi,

is there any news? Have you fixed this issue?

**Comment by danielchicote** [comment]
Hey, yes i think i fixed it.

And don't remember exactly what was the error: if the problem was causes because i was injected the blocks via php and not via xml, or if it was caused for other module that adds a cache lifetime to all blocks (aligent cacheobserver module).

**Comment by vovayatsyuk** [comment]
Glad to hear that everything is fine. I'm closing this ticket.
