### ISSUE TITLE
Also Viewed Recommendations not appearing on catalog page

### ISSUE THREAD

**Issue by mealiusman** [vovayatsyuk/magento-alsoviewed#28]
Hi,
I installed this extension in magento enterprise 1.x and configured it correctly but still not able to see also viewed products on catalog page, can you guide me in this issue?

**Comment by vovayatsyuk** [comment]
Hi,
do you see any relations in backend grids? (log or relations grids)

**Comment by mealiusman** [comment]
Yes I can see relations and log in backend grids but those entries are manual means I added from admin in product Also Viewed Tab, my question is how it will automatically update records in relations table?

**Comment by vovayatsyuk** [comment]
Log is automatically processed with cronjob. Or, you can press "process log" button at alsoviewed log page manually.

**Comment by mealiusman** [comment]
I wan thinking relations table will be automatically update whenever a visitor visit a product. Emmm but I have to setup cron job for this, got it.

**Comment by mealiusman** [comment]
One more thing how you are updating product weights in relations table? @vovayatsyuk

**Comment by vovayatsyuk** [comment]
Each log entry adds +1 to the product relations weight.

When someone opens product A, then product B, a log entry is created between A and B.
These entries are created for each visitor.

Then log entries are processed and grouped logs data gets moved into relation table.

**Comment by mealiusman** [comment]
ok, thanks for your help.
