### ISSUE TITLE
block appear before eaytabs

### ISSUE THREAD

**Issue by panteliskopsias** [vovayatsyuk/magento-alsoviewed#30]
Hello,

i just installed alsoviewed, the block appear before easytabs and not bellow, 

is that an known issue? I have made something wrong with the configuration?

**Comment by vovayatsyuk** [comment]
Yep, looks like it showing before.

You can move it with following code in local.xml of your theme:

```xml
<catalog_product_view>
    <reference name="product.info.additional">
        <action method="unsetChild"><name>alsoviewed.collateral.wrapper</name></action>
    </reference>
    <reference name="product.info.additional">
        <action method="append"><name>alsoviewed.collateral.wrapper</name></action>
    </reference>
</catalog_product_view>
```

**Comment by panteliskopsias** [comment]
i'm sorry but i don;t understand. I have not loacl.xml, i think i need to
put it in catalog.xml

but where in there?

The theme is from pagayo, pt004

2017-12-08 9:53 GMT+02:00 Vova Yatsyuk <notifications@github.com>:

**Comment by vovayatsyuk** [comment]
No, I meant local.xml

It does not exists by default, but when you’ll create it - magento will automatically read it.

https://magento.stackexchange.com/a/13253
http://inchoo.net/magento/using-local-xml-for-overriding-or-updating-xml-structure/

**Comment by panteliskopsias** [comment]
i make the /app/design/frontend/rwd/pt004/layout/local.xml
with the code
< ?xml version="1.0"?>
<layout version="0.1.0">
<catalog_product_view>
    <reference name="product.info.additional">
        <action method="unsetChild"><name>alsoviewed.collateral.wrapper</name></action>
    </reference>
    <reference name="product.info.additional">
        <action method="append"><name>alsoviewed.collateral.wrapper</name></action>
    </reference>
</catalog_product_view>
</layout>

the layout is the same [https://www.diapasonhifi.gr/elementalrb-project-audio.html](url)

**Comment by vovayatsyuk** [comment]
1. Your xml is not valid. Remove the space between `<` and `?`. Use some xml validation tool to check xml code next time. https://codebeautify.org/xmlvalidator for example.
2. Don't forget to refresh magento cache

**Comment by panteliskopsias** [comment]
Perfect! Thank you very much!

**Comment by Jeeva-Rathinam** [comment]
@vovayatsyuk  May i know where is local.xml file located?

**Comment by Jeeva-Rathinam** [comment]
@vovayatsyuk  In my case Recently Viewed widgets, how can i show "People who viewed this product also viewed" below Recently Viewed widgets. Thank you.

**Comment by vovayatsyuk** [comment]
@Jeeva-Rathinam did you try to use [solution](https://github.com/vovayatsyuk/magento-alsoviewed/issues/30#issuecomment-350197593) from this thread?

**Comment by Jeeva-Rathinam** [comment]
I have a couple of question,
1) How can i change 3 to 4 products per column: screenshot: []https://snag.gy/b0pKMm.jpg
2) I have complete knowledge about, "People also viewed these products", may i know how "You May Also like" work like how this list form.

**Comment by vovayatsyuk** [comment]
@Jeeva-Rathinam did you solve the issue with block position below recently viewed products?

P.s. please open another ticket for the rest of questions.
