### ISSUE TITLE
How "You May Also like" block Work?

### ISSUE THREAD

**Issue by Jeeva-Rathinam** [vovayatsyuk/magento-alsoviewed#31]
The block **"People who viewed this product also viewed"** work based on other user Recent viewed products list, may i know how "You May Also like" block will Work?

**Comment by vovayatsyuk** [comment]
You can specify products basis in widget and configuration: https://github.com/vovayatsyuk/magento-alsoviewed/wiki/Usage#widget

Example:

**"People who viewed this product also viewed"** - is a widget with "Build recommendations on" is set to "Current Product"

**"You May Also like"** - could be a widget with "Build recommendations on" is set to All available sources.

**Comment by Jeeva-Rathinam** [comment]
How can i bulk assign products to "Also viewed Products"  for all products?

**Comment by vovayatsyuk** [comment]
There is no such possibility.

**Comment by Jeeva-Rathinam** [comment]
I have 2 websites, 10k product website no issue, but 20k products website shows the error like : https://snag.gy/S2RE1X.jpg how can i solve this error?

**Comment by vovayatsyuk** [comment]
You should enable magento logs in configuration, and see what errors are
logged in there.

ср, 30 трав. 2018 о 11:00 Jeeva Rathinam <notifications@github.com> пише:

**Comment by Jeeva-Rathinam** [comment]
May i know how many dates it takes "People who viewed this product also viewed" applied to my all products.

**Comment by vovayatsyuk** [comment]
It depends on traffic at your store. The more visitors will browse your site, the more relations will be added.

**Comment by Jeeva-Rathinam** [comment]
may i know why Ajax not loading, screenshot : https://snag.gy/2AgUtY.jpg

**Comment by vovayatsyuk** [comment]
Please take a look at Magento's logs. They are stored in MAGENTO_ROOT/var/logs/.

Make sure you have them enabled in _System > Configuration > Developer > Logs_.

**Comment by Jeeva-Rathinam** [comment]
@vovayatsyuk there is no error in MAGENTO_ROOT/var/logs, and i have enabled System > Configuration > Developer > Logs.

**Comment by vovayatsyuk** [comment]
Then you should check PHP error logs. They are configured in the php.ini file.

**Comment by Jeeva-Rathinam** [comment]
Where is my php.ini located?

**Comment by vovayatsyuk** [comment]
Different OS has a different location for this file. I recommend you to google that question. Or, if you familiar with PHP, you can use `phpinfo()` function.

**Comment by Jeeva-Rathinam** [comment]
@vovayatsyuk there is no error in the error log, may i know the  possibilities error https://snag.gy/2AgUtY.jpg

**Comment by vovayatsyuk** [comment]
Sorry, but it's impossible to know the reason without an actual error message.

Maybe:

1. you forgot to disable Magneto's Compilation Mode?
2. not all files where uploaded?

**Comment by vovayatsyuk** [comment]
It's all about CSS styles. Here is an example: https://codepen.io/vovayatsyuk/pen/xzLgWv

**Comment by Jeeva-Rathinam** [comment]
Okay, but still Ajax problem not solved. If i click Also Viewed Products in Product Edit page, my backend and website getting stuck not loading, every time i am going to the server and restart.

**Comment by vovayatsyuk** [comment]
You have to enable PHP and Apache logs and see what is wrong.

**Comment by Jeeva-Rathinam** [comment]
@vovayatsyuk Is possible can i add **Process log** to cron, every minutes its asking process log, can i use by cron?

**Comment by vovayatsyuk** [comment]
It shoud do that with cron for every 15 minutes.

**Comment by vovayatsyuk** [comment]
Try this tutorial https://amasty.com/blog/configure-magento-cron-job/

вт, 26 черв. 2018, 07:21 користувач Jeeva Rathinam <notifications@github.com>
пише:

**Comment by Jeeva-Rathinam** [comment]
Okay, how can i give the condition like how to trigger Process log?

**Comment by vovayatsyuk** [comment]
You need to setup cron for magento only. Everything else is built-in into the module sources.

**Comment by Jeeva-Rathinam** [comment]
Just i realized by default **process log** under magento cron.

**Comment by Jeeva-Rathinam** [comment]
Every time **process log** trigger by own using Magento.

**Comment by vovayatsyuk** [comment]
Sorry, but I still don't understand you. Do you any questions?

**Comment by Jeeva-Rathinam** [comment]
@vovayatsyuk Some of the Products page empty i mean blank if temporarily disable the **magento-alsoviewed** extension the products page back to visible. May i how can i solve this issue.

Note : There is no log error, console error, nothing error will show while page blank

console error : https://snag.gy/FoEk97.jpg

**Comment by vovayatsyuk** [comment]
It’s impossible to answer your question without actual error message.

Do the following:
1. Open index.php file in magento root folder.
2. Find the following line: 
    ```
    #ini_set('display_errors', 1);
    ```
3. Uncomment it, and save the file.
4. Open the page again.

Do you see an error message now?

**Comment by vovayatsyuk** [comment]
Sorry, I don't want to be rude, but didn't you read my previous messages?

Again: **I can't help you if you don't know how to enable display_errors setting.**

**Comment by Jeeva-Rathinam** [comment]
The exception Error is : /home/giritra/public_html/app/design/frontend/base/default/template/yavva/alsoviewed/wrapper/collateral.phtml(20): Mage_Core_Block_Abstract->getChildHtml('alsoviewed.list') and my code 


```
<?php
    $_list = $this->getChild('alsoviewed.list');
    if (!$_list) :
        return;
    endif;

    $_productCollection = $_list->getProductCollection();
    if (!$_productCollection->getSize()) :
        return;
    endif;

    $_title = $_list->getTitle();
    if (null === $_title) :
        $_title = $this->getTitle();
    endif;
?>

<div class="box-collateral alsoviewed">
    <h2><?php echo $this->__($_title); ?></h2>
    <?php echo $this->getChildHtml('alsoviewed.list') ?>
</div>
```

**Comment by Jeeva-Rathinam** [comment]
Can i get any help regard blank page view after eneble **People who viewed this product also viewed**,  and please note if i enebled only **You may also like** there is no issue.

**Comment by vovayatsyuk** [comment]
Hi,

You didn't attach error message to your comment.

**Comment by vovayatsyuk** [comment]
Please double check if this template is uploaded to your server:

`/app/design/frontend/base/default/template/yavva/alsoviewed/products.phtml`

**Comment by Jeeva-Rathinam** [comment]
Yes, its uploaded.

**Comment by Jeeva-Rathinam** [comment]
@vovayatsyuk Sorry to disturb you, let me do something, thanks for your time and support.

**Comment by vovayatsyuk** [comment]
Hi,

As I already stated, I can't help you without knowing what is wrong. I need to see an error message.

If you don't know how to show an error message, please contact your hosting company.
